# Generated by Django 5.1.1 on 2024-09-27 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadfile_user_alter_uploadfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_id', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cow_id', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Lactation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parity', models.IntegerField()),
                ('parity_type', models.CharField(choices=[('primiparous', 'Primiparous'), ('multiparous', 'Multiparous')], max_length=15)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cow')),
            ],
        ),
        migrations.CreateModel(
            name='LactationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim', models.IntegerField()),
                ('date', models.DateField()),
                ('milk_yield', models.FloatField()),
                ('lactation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lactation')),
            ],
            options={
                'unique_together': {('lactation', 'dim')},
            },
        ),
    ]
