# Generated by Django 5.1.1 on 2024-10-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lactation_treatment_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimiparousFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_total_1_10', models.FloatField()),
                ('milk_total_11_20', models.FloatField()),
                ('milk_total_21_30', models.FloatField()),
                ('milk_total_31_40', models.FloatField()),
                ('milk_total_41_50', models.FloatField()),
                ('milk_total_51_60', models.FloatField()),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('b0', models.FloatField()),
                ('c', models.FloatField()),
                ('predicted_305_my', models.FloatField()),
                ('month_sin', models.FloatField()),
                ('month_cos', models.FloatField()),
                ('lactation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.lactation')),
            ],
        ),
    ]
