# Generated by Django 5.1.1 on 2024-12-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_databaseexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiparousfeatures',
            name='current_a',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='current_days_to_peak',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='current_dijkstra_b0_eqn',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='current_dijkstra_b_eqn',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='current_dijkstra_c_eqn',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='current_peak_my',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='my_variance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='predicted_persistency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='prev_a',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='prev_dijkstra_b0_eqn',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='prev_dijkstra_b_eqn',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='prev_dijkstra_c_eqn',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='prev_my_end',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='prev_peak_my',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiparousfeatures',
            name='rate_of_my_change',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
