# Generated by Django 5.1.1 on 2024-12-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_multiparousfeatures_days_to_peak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiparousfeatures',
            name='current_days_to_peak',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='multiparousfeatures',
            name='parity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='multiparousfeatures',
            name='prev_days_to_peak',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='multiparousfeatures',
            name='prev_lact_length',
            field=models.FloatField(),
        ),
    ]
