# Generated by Django 5.1.1 on 2024-12-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_multiparousfeatures_current_days_to_peak_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primiparousfeatures',
            old_name='b',
            new_name='current_dijkstra_b0_eqn',
        ),
        migrations.RenameField(
            model_name='primiparousfeatures',
            old_name='b0',
            new_name='current_dijkstra_b_b0_eqn',
        ),
        migrations.RenameField(
            model_name='primiparousfeatures',
            old_name='c',
            new_name='current_dijkstra_b_eqn',
        ),
        migrations.AddField(
            model_name='primiparousfeatures',
            name='current_dijkstra_c_eqn',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primiparousfeatures',
            name='my_variance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primiparousfeatures',
            name='rate_of_my_change',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
