services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=backend.settings
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000 